name: dictionary
description: "Dictionary project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  get: ^4.7.2
  get_storage: ^2.1.1
  sqflite_sqlcipher: ^3.1.0+1
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_messaging: ^15.2.3
  firebase_storage: ^12.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/dummy-data.db
    - assets/firebase/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300